Update bcc.yml

diff --git a/.github/workflows/bcc.yml b/.github/workflows/bcc.yml
--- a/.github/workflows/bcc.yml
+++ b/.github/workflows/bcc.yml
@@ -25,29 +25,52 @@ jobs:
           CINTENT_LOG=/home/runner/cintent/log
           echo "CINTENT_LOG=$CINTENT_LOG" >> $GITHUB_ENV
           mkdir -p $CINTENT_LOG
-  
-      - name: Start opensnoop on Linux
+
+      - name: Setup the Bash Wrapper
         if: ${{ runner.os == 'Linux' }}
         shell: bash
         run: |
-          log=${{ env.CINTENT_LOG }}/$(date +%s%N)
-          sudo opensnoop-bpfcc >> $log &
-          
-          start_time=$SECONDS
-          until [ -s "$log" ] || (( SECONDS - start_time >= 60 )); do
-            sleep 1
-          done
-          
-          if [ ! -s "$log" ]; then
-            echo "opensnoop failed to start!" 1>&2
-            exit 1
+          cat << EOF > ${{ env.CINTENT_BASH }}
+          #!/bin/bash
+          if [[ -n "${CINTENT_ENABLED}" ]]; then
+            /bin/bash "$@"
+          else
+            export CINTENT_ENABLED=true
+            
+            log=${{ env.CINTENT_LOG }}/$(date +%s%N)
+            sudo opensnoop-bpfcc >> $log &
+            pid=$!
+            
+            start_time=$SECONDS
+            until [ -s "$log" ] || (( SECONDS - start_time >= 60 )); do
+              sleep 1
+            done
+            
+            if [ ! -s "$log" ]; then
+              echo "opensnoop failed to start!" 1>&2
+              exit 1
+            fi
+            
+            /bin/bash "$@"
+
+            kill "$pid"
+            unset CINTENT_ENABLED
           fi
+          EOF
+          chmod +x ${{ env.CINTENT_BASH }}
+          echo ${{ env.CINTENT_BIN }} >> $GITHUB_PATH
   
-      - name: Testing Script
+      - name: Testing Script 1
         if: ${{ runner.os == 'Linux' }}
         shell: bash
         run: |
           python3 test.py
+
+      - name: Testing Script 2
+        if: ${{ runner.os == 'Linux' }}
+        shell: bash
+        run: |
+          python3 ignore.py
         
       - uses: actions/upload-artifact@v4
         if: ${{ runner.os == 'Linux' }}
