Update bcc.yml

diff --git a/.github/workflows/bcc.yml b/.github/workflows/bcc.yml
--- a/.github/workflows/bcc.yml
+++ b/.github/workflows/bcc.yml
@@ -30,7 +30,32 @@ jobs:
         if: ${{ runner.os == 'Linux' }}
         shell: bash
         run: |
-          cat bash_wrapper > $CINTENT_BASH
+          cat << 'EOF' > $CINTENT_BASH
+          #!/bin/bash
+          if [[ -n "${CINTENT_ENABLED}" ]]; then
+            /bin/bash "$@"
+          else
+            export CINTENT_ENABLED=true
+          
+            log=${{ env.CINTENT_LOG }}/$RANDOM
+            sudo opensnoop-bpfcc >> $log &
+            pid=$!
+            
+            start_time=$SECONDS
+            until [ -s "$log" ] || (( SECONDS - start_time >= 60 )); do
+              sleep 1
+            done
+            
+            if [ ! -s "$log" ]; then
+              echo "opensnoop failed to start!" 1>&2
+              exit 1
+            fi
+            
+            /bin/bash "$@"
+            kill "$pid"
+            unset CINTENT_ENABLED
+          fi
+          EOF          
           chmod +x ${{ env.CINTENT_BASH }}
           echo ${{ env.CINTENT_BIN }} >> $GITHUB_PATH
   
