Update instrument.yaml

diff --git a/.github/workflows/instrument.yaml b/.github/workflows/instrument.yaml
--- a/.github/workflows/instrument.yaml
+++ b/.github/workflows/instrument.yaml
@@ -7,9 +7,218 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-
-      - uses: JavidDitty/setup-cintent@371348712eba7e29bed7a88ed9b5362ea2ad974b
-
+      
+      - name: Set Environmental Variables
+        if: ${{ runner.os == 'Linux' }}
+        shell: bash
+        run: |
+          CINTENT_ARTIFACT_NAME="cintent_log"
+          echo "CINTENT_ARTIFACT_NAME=$CINTENT_ARTIFACT_NAME" >> $GITHUB_ENV
+  
+          CINTENT_BASH=/home/runner/cintent/bin/bash
+          echo "CINTENT_BASH=$CINTENT_BASH" >> $GITHUB_ENV
+  
+          CINTENT_BIN=/home/runner/cintent/bin
+          echo "CINTENT_BIN=$CINTENT_BIN" >> $GITHUB_ENV
+          mkdir -p $CINTENT_BIN
+  
+          CINTENT_BLACK=/home/runner/cintent/bin/black
+          echo "CINTENT_BLACK=$CINTENT_BLACK" >> $GITHUB_ENV
+  
+          CINTENT_FLAKE8=/home/runner/cintent/bin/flake8
+          echo "CINTENT_FLAKE8=$CINTENT_FLAKE8" >> $GITHUB_ENV
+  
+          CINTENT_LOGS=/home/runner/cintent/log
+          echo "CINTENT_LOGS=$CINTENT_LOGS" >> $GITHUB_ENV
+          mkdir -p $CINTENT_LOGS
+  
+          CINTENT_MODULE_WRAPPER=/home/runner/cintent/temp/module_wrapper
+          echo "CINTENT_MODULE_WRAPPER=$CINTENT_MODULE_WRAPPER" >> $GITHUB_ENV
+  
+          CINTENT_MYPY=/home/runner/cintent/bin/mypy
+          echo "CINTENT_MYPY=$CINTENT_MYPY" >> $GITHUB_ENV
+  
+          CINTENT_NOX=/home/runner/cintent/bin/nox
+          echo "CINTENT_NOX=$CINTENT_NOX" >> $GITHUB_ENV
+  
+          CINTENT_POETRY=/home/runner/cintent/bin/poetry
+          echo "CINTENT_POETRY=$CINTENT_POETRY" >> $GITHUB_ENV
+  
+          CINTENT_PYTHON=/home/runner/cintent/bin/python
+          echo "CINTENT_PYTHON=$CINTENT_PYTHON" >> $GITHUB_ENV
+  
+          CINTENT_PYTHON_WRAPPER=/home/runner/cintent/temp/python_wrapper
+          echo "CINTENT_PYTHON_WRAPPER=$CINTENT_PYTHON_WRAPPER" >> $GITHUB_ENV
+  
+          CINTENT_PYTHON3=/home/runner/cintent/bin/python3
+          echo "CINTENT_PYTHON3=$CINTENT_PYTHON3" >> $GITHUB_ENV
+  
+          CINTENT_PYLINT=/home/runner/cintent/bin/pylint
+          echo "CINTENT_PYLINT=$CINTENT_PYLINT" >> $GITHUB_ENV
+  
+          CINTENT_PYTEST=/home/runner/cintent/bin/pytest
+          echo "CINTENT_PYTEST=$CINTENT_PYTEST" >> $GITHUB_ENV
+  
+          CINTENT_RUFF=/home/runner/cintent/bin/ruff
+          echo "CINTENT_RUFF=$CINTENT_RUFF" >> $GITHUB_ENV
+  
+          CINTENT_STEP_ID=0
+          echo "CINTENT_STEP_ID=$CINTENT_STEP_ID" >> $GITHUB_ENV
+  
+          CINTENT_TEMP=/home/runner/cintent/temp
+          echo "CINTENT_TEMP=$CINTENT_TEMP" >> $GITHUB_ENV
+          mkdir -p $CINTENT_TEMP
+  
+          CINTENT_TOX=/home/runner/cintent/bin/tox
+          echo "CINTENT_TOX=$CINTENT_TOX" >> $GITHUB_ENV
+  
+          CINTENT_UV=/home/runner/cintent/bin/uv
+          echo "CINTENT_UV=$CINTENT_UV" >> $GITHUB_ENV
+  
+          CINTENT_XDOCTEST=/home/runner/cintent/bin/xdoctest
+          echo "CINTENT_XDOCTEST=$CINTENT_XDOCTEST" >> $GITHUB_ENV
+  
+      - name: Write Bash Wrappers
+        if: ${{ runner.os == 'Linux' }}
+        shell: bash
+        run: |
+          # Save the current matrix configurations
+          echo "${{ toJson(matrix) }}" > matrix_context.json
+          CINTENT_MATRIX=$(cat matrix_context.json | tr -s '\n' ' ')
+          echo "CINTENT_MATRIX=$CINTENT_MATRIX" >> $GITHUB_ENV
+  
+          # Write the bash wrapper
+          cat << 'WRAPPER_EOF' > ${{ env.CINTENT_BASH }}
+          #!/bin/bash
+          if [[ -z "${CINTENT_IS_TRACING_BASH}" ]]; then
+            # Set tracer indicator
+            export CINTENT_IS_TRACING_BASH=true
+            echo "CINTENT_IS_TRACING_BASH=$CINTENT_IS_TRACING_BASH" >> $GITHUB_ENV
+  
+            # Increment the step id
+            CINTENT_STEP_ID=$((CINTENT_STEP_ID+1))
+            echo "CINTENT_STEP_ID=$CINTENT_STEP_ID" >> "$GITHUB_ENV"
+            
+            # Define the log paths
+            timestamp=$(date +%s%N)
+            metadata_log=$CINTENT_LOGS/$timestamp.$CINTENT_STEP_ID.metadata.txt
+            execsnoop_log=$CINTENT_LOGS/$timestamp.$CINTENT_STEP_ID.execsnoop.txt
+            opensnoop_log=$CINTENT_LOGS/$timestamp.$CINTENT_STEP_ID.opensnoop.txt
+            
+            # Create the metadata log
+            echo -en \
+            "repository = $GITHUB_REPOSITORY\n"\
+            "branch = $GITHUB_REF_NAME\n"\
+            "commit = $GITHUB_SHA\n"\
+            "workflow = ${GITHUB_WORKFLOW_REF%@*}\n"\
+            "run_number = $GITHUB_RUN_NUMBER\n"\
+            "run_attempt = $GITHUB_RUN_ATTEMPT\n"\
+            "workspace = $GITHUB_WORKSPACE\n"\
+            "job_id = $GITHUB_JOB\n"\
+            "matrix = $CINTENT_MATRIX\n"\
+            "step_id = $CINTENT_STEP_ID\n"\
+            > "$metadata_log"
+            sed -i 's/^[ ]*//' "$metadata_log"
+  
+            # Start snooping tools and pipe their outputs to their logs
+            sudo execsnoop-bpfcc -qtx > "$execsnoop_log" 2> /dev/null &
+            sudo opensnoop-bpfcc -eT -n python > "$opensnoop_log" 2> /dev/null &
+        
+            # Wait for snooping tools to start tracing (or timeout)
+            timeout_time=60
+            start_time=$SECONDS
+            current_time=$((SECONDS - start_time))
+            execsnoop_search="TIME(s)\s+PCOMM\s+PID\s+PPID\s+RET\s+ARGS"
+            opensnoop_search="TIME(s)\s+PID\s+COMM\s+FD\s+ERR\s+FLAGS\s+PATH"
+            until grep -q "$execsnoop_search" "$execsnoop_log" && grep -q "$opensnoop_search" "$opensnoop_log" || [[ "$current_time" -gt "$timeout_time" ]]; do
+              sleep 1
+              current_time=$((SECONDS - start_time))
+            done
+            if grep -q "$execsnoop_search" "$execsnoop_log"; then
+              echo "execsnoop failed to start!" 1>&2
+              exit 1
+            fi
+            if grep -q "$opensnoop_search" "$opensnoop_log"; then
+              echo "opensnoop failed to start!" 1>&2
+              exit 1
+            fi
+  
+            # (Re-)Apply the wrapper(s)
+            export PATH="${{ env.CINTENT_BIN }}:$PATH"
+            echo ${{ env.CINTENT_BIN }} >> $GITHUB_PATH
+  
+            # Start the bash script
+            echo "start_time = $(date +%s)" >> $metadata_log
+            /bin/bash "$@"
+            echo "end_time = $(date +%s)" >> $metadata_log
+  
+            # (Re-)Apply the wrapper(s)
+            export PATH="${{ env.CINTENT_BIN }}:$PATH"
+            echo ${{ env.CINTENT_BIN }} >> $GITHUB_PATH
+  
+            # Unset tracer indicator
+            unset CINTENT_IS_TRACING_BASH
+            echo "CINTENT_IS_TRACING_BASH=" >> $GITHUB_ENV
+          else
+            # (Re-)Apply the wrapper(s)
+            export PATH="${{ env.CINTENT_BIN }}:$PATH"
+            echo ${{ env.CINTENT_BIN }} >> $GITHUB_PATH
+  
+            # Start the bash script
+            /bin/bash "$@"
+  
+            # (Re-)Apply the wrapper(s)
+            export PATH="${{ env.CINTENT_BIN }}:$PATH"
+            echo ${{ env.CINTENT_BIN }} >> $GITHUB_PATH
+          fi
+          WRAPPER_EOF
+          chmod +x ${{ env.CINTENT_BASH }}
+  
+      - name: Write Python Wrappers
+        if: ${{ runner.os == 'Linux' }}
+        shell: bash
+        run: |
+          cat << 'WRAPPER_EOF' > ${{ env.CINTENT_PYTHON_WRAPPER }}
+          #!/bin/bash
+          log_path="$CINTENT_LOGS/$(date +%s%N).$CINTENT_STEP_ID.scalene.json"
+          pip show scalene > /dev/null 2>&1 || pip install scalene
+          scalene run --outfile "$log_path" --cpu-only --profile-all --cpu-percent-threshold 0 --cpu-sampling-rate 0.01 --malloc-threshold 0 --stacks "$@"
+          WRAPPER_EOF
+          sudo chmod +x ${{ env.CINTENT_PYTHON_WRAPPER }}
+          sudo cp ${{ env.CINTENT_PYTHON_WRAPPER }} ${{ env.CINTENT_PYTHON }}
+          sudo cp ${{ env.CINTENT_PYTHON_WRAPPER }} ${{ env.CINTENT_PYTHON3 }}
+      
+      - name: Write Module Wrappers
+        if: ${{ runner.os == 'Linux' }}
+        shell: bash
+        run: |
+          cat << 'WRAPPER_EOF' > ${{ env.CINTENT_MODULE_WRAPPER }}
+          #!/bin/bash
+          log_path="$CINTENT_LOGS/$(date +%s%N).$CINTENT_STEP_ID.scalene.json"
+          pip show scalene > /dev/null 2>&1 || pip install scalene
+          echo "scalene run --outfile "$log_path" --cpu-only --profile-all --cpu-percent-threshold 0 --cpu-sampling-rate 0.01 --malloc-threshold 0 --stacks -m " "$@"
+          scalene run --outfile "$log_path" --cpu-only --profile-all --cpu-percent-threshold 0 --cpu-sampling-rate 0.01 --malloc-threshold 0 --stacks -m "$@"
+          WRAPPER_EOF
+          sudo chmod +x ${{ env.CINTENT_MODULE_WRAPPER }}
+          sudo cp ${{ env.CINTENT_MODULE_WRAPPER }} ${{ env.CINTENT_BLACK }}
+          sudo cp ${{ env.CINTENT_MODULE_WRAPPER }} ${{ env.CINTENT_FLAKE8 }}
+          sudo cp ${{ env.CINTENT_MODULE_WRAPPER }} ${{ env.CINTENT_MYPY }}
+          sudo cp ${{ env.CINTENT_MODULE_WRAPPER }} ${{ env.CINTENT_NOX }}
+          sudo cp ${{ env.CINTENT_MODULE_WRAPPER }} ${{ env.CINTENT_POETRY }}
+          sudo cp ${{ env.CINTENT_MODULE_WRAPPER }} ${{ env.CINTENT_PYLINT }}
+          sudo cp ${{ env.CINTENT_MODULE_WRAPPER }} ${{ env.CINTENT_PYTEST }}
+          sudo cp ${{ env.CINTENT_MODULE_WRAPPER }} ${{ env.CINTENT_RUFF }}
+          sudo cp ${{ env.CINTENT_MODULE_WRAPPER }} ${{ env.CINTENT_TOX }}
+          sudo cp ${{ env.CINTENT_MODULE_WRAPPER }} ${{ env.CINTENT_UV }}
+          sudo cp ${{ env.CINTENT_MODULE_WRAPPER }} ${{ env.CINTENT_XDOCTEST }}
+  
+      - name: Apply Wrappers
+        if: ${{ runner.os == 'Linux' }}
+        shell: bash
+        run: |
+          export PATH="${{ env.CINTENT_BIN }}:$PATH"
+          echo ${{ env.CINTENT_BIN }} >> $GITHUB_PATH
+        
       - uses: actions/setup-python@v6
         with:
           python-version: '3.13' 
@@ -24,9 +233,9 @@ jobs:
           pip install pytest
           pytest
           
-      - name: Upload CIntent Artifacts
-        uses: actions/upload-artifact@v4
-        if: always()
-        with:
-          name: ${{ env.CINTENT_ARTIFACT_NAME }}
-          path: ${{ env.CINTENT_LOGS }}
+      # - name: Upload CIntent Artifacts
+      #   uses: actions/upload-artifact@v4
+      #   if: always()
+      #   with:
+      #     name: ${{ env.CINTENT_ARTIFACT_NAME }}
+      #     path: ${{ env.CINTENT_LOGS }}
