Update instrument.yaml

diff --git a/.github/workflows/instrument.yaml b/.github/workflows/instrument.yaml
--- a/.github/workflows/instrument.yaml
+++ b/.github/workflows/instrument.yaml
@@ -149,7 +149,51 @@ jobs:
           cat << 'BASH_WRAPPER_EOF' > ${{ env.CINTENT_BASH }}
           #!/bin/bash
           if [[ -z "${CINTENT_IS_TRACING_BASH}" ]]; then
+            export CINTENT_IS_TRACING_BASH=true
+            echo "CINTENT_IS_TRACING_BASH=$CINTENT_IS_TRACING_BASH" >> "$GITHUB_ENV"
+            CINTENT_STEP_ID=$((CINTENT_STEP_ID+1))
+            echo "CINTENT_STEP_ID=$CINTENT_STEP_ID" >> "$GITHUB_ENV"
+            
+            # Define the log paths
+            timestamp=$(date +%s%N)
+            metadata_log=$CINTENT_LOGS/$timestamp.$CINTENT_STEP_ID.metadata.txt
+            execsnoop_log=$CINTENT_LOGS/$timestamp.$CINTENT_STEP_ID.execsnoop.txt
+            strace_log=$CINTENT_LOGS/$timestamp.$CINTENT_STEP_ID.strace.txt
+            
+            # Create the metadata log
+            echo -en \
+            "repository = $GITHUB_REPOSITORY\n"\
+            "branch = $GITHUB_REF_NAME\n"\
+            "commit = $GITHUB_SHA\n"\
+            "workflow = ${GITHUB_WORKFLOW_REF%@*}\n"\
+            "run_number = $GITHUB_RUN_NUMBER\n"\
+            "run_attempt = $GITHUB_RUN_ATTEMPT\n"\
+            "workspace = $GITHUB_WORKSPACE\n"\
+            "job_id = $GITHUB_JOB\n"\
+            "matrix = $CINTENT_MATRIX\n"\
+            "step_id = $CINTENT_STEP_ID\n"\
+            > "$metadata_log"
+            sed -i 's/^[ ]*//' "$metadata_log"
+            
+            # Start execsnoop and pipe its output to the execsnoop log
+            sudo execsnoop-bpfcc -qx >> "$execsnoop_log" 2> /dev/null &
+        
+            # Wait for execsnoop to start tracing (or timeout)
+            timeout_time=60
+            start_time=$SECONDS
+            current_time=$((SECONDS - start_time))
+            until [[ -s "$execsnoop_log" || "$current_time" -gt "$timeout_time" ]]; do
+              sleep 1
+              current_time=$((SECONDS - start_time))
+            done
+            if [[ ! -s "$execsnoop_log" ]]; then
+              echo "execsnoop failed to start!" 1>&2
+              exit 1
+            fi
+            
             /bin/bash "$@"
+            unset CINTENT_IS_TRACING_BASH
+            echo "CINTENT_IS_TRACING_BASH=" >> "$GITHUB_ENV"
           else
             /bin/bash "$@"
           fi
